version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      # check Java version
      - echo *** Java version ***
      - java -version
  build:
    commands:
      # build
      - echo Building ..
      - mvn package
      - echo env $ENV
      - echo $ENV > env.txt
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - env.txt
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes